# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
default_stages: [pre-commit]  # run hooks on commit unless specified otherwise

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3298dda  # v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: \.patch$
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        exclude: ".*.svg"
      - id: check-merge-conflict

  - repo: https://github.com/hadialqattan/pycln
    rev: 14197bf  # v2.5.0
    hooks:
      - id: pycln
        args: ["--config", ".pycln-config.yaml"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pycqa/isort
    rev: e44834b  # 5.12.0
    hooks:
      - id: isort
        args: ["--line-length=120", "--profile", "black"]

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1238e1d  # 1.13.0
    hooks:
      - id: blacken-docs

  - repo: https://github.com/adrienverge/yamllint.git
    rev: 9cce294  # v1.28.0
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict]

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 07f6707  # 6.3.0
    hooks:
      - id: pydocstyle
        types_or: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    # MyPy checks for type annotations.
    rev: "6e63c9e"
    hooks:
      - id: mypy
        args: [--python-version=3.12, --ignore-missing-imports]
        additional_dependencies: [types-PyYAML]
